### ISSUE TITLE
hello, Sachin. some questions for you :)

### ISSUE THREAD

**Issue by AlexanderKott** [droid-lover/FunFacts#1]
Hello, Sachin
I really appreciate your work, this is your repo. It really helps to understand the basics of modular applications. I am still continuing to learn from your projects here. May I ask you questions related to this repo / project?

**Comment by droid-lover** [comment]
Hi @AlexanderKott Thanks for liking my work, please check the article for full explanation . please let me know if any more questions

https://medium.com/native-mobile-bits/modular-android-app-architecture-build-to-scale-d6f402cbd93a
